// <auto-generated />
using System;
using Drivers.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Drivers.Migrations
{
    [DbContext(typeof(TripContext))]
    [Migration("20200601173452_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Drivers.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("avgSpeed");

                    b.Property<DateTime>("created_at");

                    b.Property<string>("driver")
                        .IsRequired();

                    b.Property<DateTime>("end");

                    b.Property<double>("miles");

                    b.Property<DateTime>("start");

                    b.Property<double>("totalTimeDriven");

                    b.Property<DateTime>("updated_at");

                    b.HasKey("Id");

                    b.ToTable("trip");
                });
#pragma warning restore 612, 618
        }
    }
}
